FROM python:3.11

ENV PYTHONUNBUFFERED 1

RUN mkdir /app
WORKDIR /app
ADD . /app/
RUN pip install poetry
RUN poetry install --with check
RUN poetry self add 'poethepoet[poetry_plugin]'

EXPOSE 8080
CMD ["poetry", "poe", "qa"]
